[project]
name = "python-upskilling"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.45.1",
    "streamlit-code-editor>=0.1.22",
    "streamlit-local-storage>=0.0.25",
]
