[project]
name = "python-fastskilling"
version = "1.0.0"
description = "Python learning platform for kick off with Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "streamlit>=1.45.1",
    "streamlit-code-editor>=0.1.22",
    "streamlit-local-storage>=0.0.25",
]
